### ISSUE TITLE
AMEX card should start with only 37 or 34, but AMEX UPI accepts any 15 digit card number

### ISSUE THREAD

**Issue by Joyosmit** [RedeemApp/cc-billpay-upi-id#10]
As per the documentation in AMEX page, their cards start with only 37 or 34. However, UPI ID is being generated even for card not starting with 37 or 34
![AMEX_STUFF](https://github.com/user-attachments/assets/16d506f7-6dd3-4493-829c-3f136e6e1ef5)

**Comment by mkagenius** [comment]
This should be done as part of https://github.com/RedeemApp/cc-billpay-upi-id/issues/4 
as that handles other cards as well along with amex.

**Comment by Joyosmit** [comment]
Understood
