### ISSUE TITLE
[Feature] Add QR code for UPI scanning in case of desktop.

### ISSUE THREAD

**Issue by mkagenius** [RedeemApp/cc-billpay-upi-id#2]

**Comment by preetmungara** [comment]
Hi, I would like to work on it. can you please assign to me if anyone isn't working.

**Comment by preetmungara** [comment]
I've opened this PR as part of this, can you please check.  https://github.com/RedeemApp/cc-billpay-upi-id/pull/6

**Comment by mkagenius** [comment]
This was merged. https://github.com/RedeemApp/cc-billpay-upi-id/pull/6
